### ISSUE TITLE
2.4.7 Missing `coerce_shell_command' for DockerCookbook::DockerBase:Class under vagrant/chef-solo/berkshelf

### ISSUE THREAD

**Issue by evansde77** [chef-cookbooks/docker#621] opened 2016-01-29 19:56 UTC
### Environment: 

Running on Mac OSX 10.11.3, using VirtualBox:
chef-solo -v
Chef: 12.6.0
berks -v
4.0.1

vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
 
vagrant plugin list
vagrant-berkshelf (4.1.0)
vagrant-share (1.1.5, system)

docker cookbook version 2.4.7

### Scenario:
During provisioning of a VM with vagrant/chef-solo the docker cookbook fails to load with a 
NoMethodError
undefined method `coerce_shell_command' for DockerCookbook::DockerBase:Class
Full traceback can be seen here: 
https://gist.github.com/evansde77/8901a70e8c31dd718146#file-chef-output

At first I suspected this was something I had done, so I stripped it down and reproduced the issue in a bare new berks cookbook just by adding the docker cookbook as a dependency in the metadata.rb for the cookbook and provisioning. 
Reverting the docker cookbook version from 2.4.7 to 2.4.5 allowed provisioning to proceed. 

### Steps to Reproduce:
I outlined the steps to reproduce this in this gist:

https://gist.github.com/evansde77/8901a70e8c31dd718146

Essentially, adding the docker cookbook dependency to the metadata.rb triggers the problem 

### Expected Result:

Adding the cookbook as a dependency should let the cookbook compile during the chef run. 

### Actual Result:

Provisioning step fails with the traceback linked above

**Comment by NickMRamirez** [comment] 2016-01-30 04:45
I have been getting the same error on Windows.
Host OS: Windows 10
Vagrant: version 1.8.1
Guest OS: Ubuntu 15.04

It was very strange because it happened non-stop on one computer. 

I found that changing the docker cookbook that was cached in Berkshelf so that I could *puts* the instance_methods of the class showed that the method *was* defined. I was at a loss. 

I tried it out on another computer...and it worked fine. But now it's happening on that computer too. Not sure what changed...

The docker cookbook worked all day earlier today on the original computer where it had not been working! And now back to not working on this second computer.

**Comment by someara** [comment] 2016-01-30 06:47
Does this still happen on v2.4.9?

**Comment by NickMRamirez** [comment] 2016-01-30 16:19
@someara No, version 2.4.9 did not solve the problem for me. I think the problem is that this line in [docker_base.rb](https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_base.rb):

```ruby
include DockerHelpers::Base
```

does not allow the class `DockerBase` to call methods defined in the included file. I think it *would* allow an *instance* of DockerBase to call the methods, but not from within the class definition itself. (I'm not super familiar with ruby includes, but it seems to be the case, but I found this: http://stackoverflow.com/questions/15097929/ruby-module-require-and-include#answer-15098219).

Having an `include` and an `extend` seems to work:

```ruby
include DockerHelpers::Base
extend DockerHelpers::Base
```

The addition of `extend` may also be needed in [docker_container.rb](https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb) and [docker_service_base.rb](https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_service_base.rb)

**Comment by NickMRamirez** [comment] 2016-01-30 18:01
Pull request #622

**Comment by someara** [comment] 2016-01-30 19:34
I can't reproduce this with test-kitchen no matter how hard I try.

I've tried manually specifying compat_resource 12.5.23, 12.5.24, 12.5.25 and 12.5.26 and they all converge without a problem. 

12.7.0 throws enough errors and warnings that I'm considering it broken.

@jkeiser does PR #622 give any clues to what's going on?

Perhaps there is some brokenness with the vagrant-berkshelf?

PS: you should **really** be using test-kitchen to drive Vagrant. The vagrant-berkshelf plugin injects cookbooks into the machine using Serious Hacks. Test-kitchen handles this properly. The vagrant-berkshelf was deprecated years ago and is no longer maintained.

**Comment by NickMRamirez** [comment] 2016-01-30 19:38
@someara I'll have to give TestKitchen a try some time. I had tried it about a year ago and it didn't seem to work on a Windows host.

**Comment by NickMRamirez** [comment] 2016-01-30 19:42
[This is the project](https://github.com/NickMRamirez/haproxy_project) that I was using that was seeing the error. It uses Vagrant to spin up a VM, then uses the docker cookbook to install Docker.

**Comment by evansde77** [comment] 2016-02-01 21:27
can confirm that this issue isnt present under test kitchen, so since that seems to be the new weapon of choice ill switch to that.

**Comment by NickMRamirez** [comment] 2016-02-01 22:27
@evansde77 Dave, if not too much trouble, could you test my fix before switching to Test Kitchen. It fixes it for me, but someone else will have to verify that it fixes it for them and so far you're the only one who has reported it.

**Comment by evansde77** [comment] 2016-02-01 23:02
@NickMRamirez I cloned your version of the docker cookbook and re-ran, it looks like it fixed the problem but there is a lot of other noise there. Output here: https://gist.github.com/evansde77/0b0aaf36bdb984a7c42a

**Comment by NickMRamirez** [comment] 2016-02-02 02:03
Hmm...I see those messages too. I don't think they're related. They seem to be talking about how properties have a default value of nil and how there's a null reference when calling a method called validate.

**Comment by jamime** [comment] 2016-02-02 17:35
Also experiencing this. Cookbook runs fine when using test kitchen but when using vagrant & chef_zero provisioner I get the same error.

**Comment by someara** [comment] 2016-02-03 08:34
Okay I'm starting to see this on travis -
https://travis-ci.org/chef-cookbooks/docker/builds/106678195

**Comment by jamime** [comment] 2016-02-04 09:26
Anything we can do to help diagnose?

**Comment by NickMRamirez** [comment] 2016-02-04 12:48
It seems like it has to do with the scope of the methods and how they are being brought into the class using `include`, and not `extend`. Pull request #622 is my fix for it. The mystery is why it works in some places (TestKitchen) and not others. In fact, I'm pretty sure it *was* working with chef zero at one point, or maybe even intermittently working. 

Is this a language-level difference? Does TestKitchen use an older or newer version of ruby?

**Comment by someara** [comment] 2016-02-04 13:23
Upgrading to compat_resource 12.7.1 seems to have fixed this in travis.

Why Vagrant was failing remains a mystery. Closing for now.

-s

**Closed by someara** 2016-02-04 13:23 UTC

**Comment by NickMRamirez** [comment] 2016-02-04 14:51
The update to compat_resource fixes it for me. I'll close the pull request.

**Comment by jamime** [comment] 2016-02-04 14:57
Fixed for me also. Thanks.

**Comment by barryku** [comment] 2016-02-17 03:02
For those who don't know how to upgrade compat_resources alone like me.  You can change your docker cookbook to 2.4.24 or later, and do _berks update docker_ will update docker along with compat_resources 12.7.1.  I  had using docker 2.4.10 that was working two weeks ago.
