### ISSUE TITLE
Container being redeployed at every chef-run

### ISSUE THREAD

**Issue by jperville** [chef-cookbooks/docker#597] opened 2016-01-05 10:34 UTC
Currently using version 2.4.0 of this cookbook.

My global docker_service resource is configured to use `log_driver 'fluentd'` and `log_opts "fluentd-address=127.0.0.1:24224"`.
I have a docker_container that I explicitly configured to use `log_driver 'json-file'` and explicitly specifies `log_opts Hash.new`.

At each chef-run, that docker_container is redeployed with the following trace:

```
    * docker_container[registrator] action run
      - stopping registrator 
      - deleting registrator
      - update registrator
      -   set exposed_ports to {} (was nil)
      -   set log_opts      to {} (was {"fluentd-address"=>"127.0.0.1:24224"})
      - starting registrator
```

Please note that here is how the docker-inspect looks like:
```sh
root@staging4-compute:~# docker inspect -f '{{.HostConfig.LogConfig}}' registrator
{json-file map[fluentd-address:127.0.0.1:24224]}
```
Also note that the image I am using (`gliderlabs/registrator:v6`) is not exposing any port.

I believe that the redeploy is due to incorrect attribute merging for the log_opts attribute; docker blindly reuses the docker_service value (even if it is incorrect for the container's log-driver and if docker won't start the container if I supply incorrect values for the log_opts) and I have no way to tell the cookbook explicitly to use `Hash.new` as the log_opts (the cookbook thinks that what I supplied is the default value and won't override the docker-supplied incorrect value).

**Comment by jperville** [comment] 2016-01-20 08:28
Hi @someara , I'm still having the issue with 2.4.3 (after fixing a bug with immutable array for which I'm about to submit a PR). Please consider reopening.

```
    * docker_container[registrator] action run
      - stopping registrator 
      - deleting registrator
      - update registrator
      -   set exposed_ports to {} (was nil)
      -   set log_opts      to {} (was {"fluentd-address"=>"127.0.0.1:24224"})
      - starting registrator
```

**Comment by scalp42** [comment] 2016-01-20 18:00
@someara correct I'm seeing containers being redeployed as well here:

```
  * docker_container[mysql] action create
    - stopping mysql
    - deleting mysql
    - update mysql
    -   set volumes to nil (was {"/var/lib/mysql"=>{}})
  * docker_container[mysql] action run
    - deleting mysql
    - update mysql
    -   set volumes to nil (was {"/var/lib/mysql"=>{}})
    - starting mysql
```

Recipe pretty straightforward:

```ruby
docker_image 'mysql' do
  tag node[cookbook_name]['version']
  if node['is_packer']
    action :nothing
  else
    action node[cookbook_name]['docker'] ? :pull : :nothing
  end
end

docker_container 'mysql' do
  tag node[cookbook_name]['version']
  port '3306:3306'
  network_mode 'bridge'
  restart_policy 'always' # on-failure:10 always
  env 'MYSQL_ROOT_PASSWORD=dev'
  binds [%|#{::File.join(node['gz-docker']['docker_mount'], 'mysql')}:/etc/mysql/conf.d|]
  if node['is_packer']
    action :nothing
  else
    action node[cookbook_name]['docker'] ? [:create, :run] : [:delete, :stop]
  end
end
```

**Comment by chasebolt** [comment] 2016-01-20 18:04
@scalp42 change binds to volumes and see if that fixes it

**Comment by scalp42** [comment] 2016-01-20 18:05
@chasebolt give me 5 mins

**Comment by scalp42** [comment] 2016-01-20 18:08
@chasebolt same issue with `volumes`.

**Comment by chasebolt** [comment] 2016-01-20 18:08
@scalp42 nm i dont think that is the issue. i think this is from a load_current_value issue @someara and I have been discussing.

try removing the docker container manually. then run chef so it creates a brand new container. it shouldnt redeploy after that.

**Comment by scalp42** [comment] 2016-01-20 18:12
@chasebolt unfortunately, these are new boxes.

I tried just to be sure, deleted the container and re-ran Chef twice:

1st run:

```
 * docker_image[mysql] action pull (up to date)
  * docker_container[mysql] action create
    - create mysql
    -   set container_name              to "mysql" (default value)
    -   set repo                        to "mysql" (default value)
    -   set tag                         to "5.6"
    -   set command                     to nil (default value)
    -   set cap_add                     to nil (default value)
    -   set cap_drop                    to nil (default value)
    -   set cgroup_parent               to "" (default value)
    -   set cpu_shares                  to 0 (default value)
    -   set cpuset_cpus                 to "" (default value)
    -   set devices                     to nil (default value)
    -   set dns                         to nil (default value)
    -   set dns_search                  to nil (default value)
    -   set domain_name                 to "" (default value)
    -   set entrypoint                  to nil (default value)
    -   set env                         to ["MYSQL_ROOT_PASSWORD=dev"]
    -   set extra_hosts                 to nil (default value)
    -   set exposed_ports               to {"3306/tcp"=>{}}
    -   set hostname                    to nil (default value)
    -   set ipc_mode                    to nil (default value)
    -   set labels                      to nil (default value)
    -   set links                       to nil (default value)
    -   set log_driver                  to "json-file" (default value)
    -   set log_opts                    to nil (default value)
    -   set mac_address                 to nil (default value)
    -   set memory                      to 0 (default value)
    -   set memory_swap                 to -1 (default value)
    -   set network_disabled            to false (default value)
    -   set network_mode                to "bridge"
    -   set outfile                     to nil (default value)
    -   set port_bindings               to {"3306/tcp"=>[{"HostIp"=>"0.0.0.0", "HostPort"=>"3306"}]}
    -   set pid_mode                    to nil (default value)
    -   set privileged                  to false (default value)
    -   set publish_all_ports           to false (default value)
    -   set remove_volumes              to false (default value)
    -   set restart_maximum_retry_count to 0 (default value)
    -   set restart_policy              to "always"
    -   set security_opts               to [""] (default value)
    -   set signal                      to "SIGKILL" (default value)
    -   set tty                         to false (default value)
    -   set ulimits                     to nil (default value)
    -   set user                        to "" (default value)
    -   set volumes                     to nil
    -   set volumes_from                to nil (default value)
    -   set working_dir                 to nil (default value)
  * docker_container[mysql] action run
    - deleting mysql
```

2nd run:

```
  * docker_container[mysql] action run
    - deleting mysql
    - update mysql
    -   set volumes to nil (was {"/var/lib/mysql"=>{}})
    - starting mysql
```

**Comment by chasebolt** [comment] 2016-01-20 18:17
im confused on the first run showing `-   set volumes                     to nil`. if volumes is nil then i dont see how it created it with `{"/var/lib/mysql"=>{}}`.

after the first run can you dump docker inspect on the container.

**Comment by scalp42** [comment] 2016-01-20 18:25
Using same recipe with `2.4.1`:

```
  * docker_container[mysql] action create
    - stopping mysql
    - deleting mysql
    - update mysql
    -   set volumes to {"/docker_mount/mysql:/etc/mysql/conf.d"=>{}} (was {"/var/lib/mysql"=>{}})
  * docker_container[mysql] action run
    - starting mysql
```

**Comment by scalp42** [comment] 2016-01-20 18:25
I'll do docker inspect on both versions, give me a few.

**Comment by scalp42** [comment] 2016-01-20 18:31
With `2.4.2`, deleted container then:

1st run:

```
[
{
    "Id": "d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b",
    "Created": "2016-01-20T18:27:09.511328479Z",
    "Path": "/entrypoint.sh",
    "Args": [
        "mysqld"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 3202,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-20T18:27:09.642716169Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7",
    "ResolvConfPath": "/docker/containers/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/resolv.conf",
    "HostnamePath": "/docker/containers/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/hostname",
    "HostsPath": "/docker/containers/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/hosts",
    "LogPath": "/docker/containers/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b-json.log",
    "Name": "/mysql",
    "RestartCount": 0,
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/docker_mount/mysql:/etc/mysql/conf.d"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": -1,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": null,
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {
                "max-file": "10",
                "max-size": "5m"
            }
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "overlay",
        "Data": {
            "LowerDir": "/docker/overlay/402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7/root",
            "MergedDir": "/docker/overlay/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/merged",
            "UpperDir": "/docker/overlay/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/upper",
            "WorkDir": "/docker/overlay/d1edfa9ff43bc459cac07786e752e47d2f747f24946c6b1ecbee00c89bcca21b/work"
        }
    },
    "Mounts": [
        {
            "Source": "/docker_mount/mysql",
            "Destination": "/etc/mysql/conf.d",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "b28e4b938ba3b15783326aa38d8fbf7ff2f60ee3480f6822a22133cd08e88f21",
            "Source": "/docker/volumes/b28e4b938ba3b15783326aa38d8fbf7ff2f60ee3480f6822a22133cd08e88f21/_data",
            "Destination": "/var/lib/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "d1edfa9ff43b",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3306/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "MYSQL_ROOT_PASSWORD=dev",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "MYSQL_MAJOR=5.6",
            "MYSQL_VERSION=5.6.28-1debian8"
        ],
        "Cmd": [
            "mysqld"
        ],
        "Image": "mysql:5.6",
        "Volumes": {
            "/var/lib/mysql": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {}
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "ce918a7ebb08d08ebac930390bfadead84aea232ff3e99b1a60c3dc25b5111ce",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/ce918a7ebb08",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "b7e37436869ed2141689937b20a13f5ae79c6c995e92908824603e3d49f81507",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:03",
        "Networks": {
            "bridge": {
                "EndpointID": "b7e37436869ed2141689937b20a13f5ae79c6c995e92908824603e3d49f81507",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:03"
            }
        }
    }
}
]
```

2nd run:

```
[
{
    "Id": "e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b",
    "Created": "2016-01-20T18:29:25.527224513Z",
    "Path": "/entrypoint.sh",
    "Args": [
        "mysqld"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 5222,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-20T18:29:25.778691655Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7",
    "ResolvConfPath": "/docker/containers/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/resolv.conf",
    "HostnamePath": "/docker/containers/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/hostname",
    "HostsPath": "/docker/containers/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/hosts",
    "LogPath": "/docker/containers/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b-json.log",
    "Name": "/mysql",
    "RestartCount": 0,
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/docker_mount/mysql:/etc/mysql/conf.d"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": -1,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": null,
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {
                "max-file": "10",
                "max-size": "5m"
            }
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "overlay",
        "Data": {
            "LowerDir": "/docker/overlay/402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7/root",
            "MergedDir": "/docker/overlay/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/merged",
            "UpperDir": "/docker/overlay/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/upper",
            "WorkDir": "/docker/overlay/e16bcf6d998e0a19f96fbf78f15aa60b3688282ec7f8365160c9892cd9c9ec1b/work"
        }
    },
    "Mounts": [
        {
            "Source": "/docker_mount/mysql",
            "Destination": "/etc/mysql/conf.d",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "db7d026b8425035b1628a703cd1a7346c2819518f974284f97b67d09c27e401b",
            "Source": "/docker/volumes/db7d026b8425035b1628a703cd1a7346c2819518f974284f97b67d09c27e401b/_data",
            "Destination": "/var/lib/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "e16bcf6d998e",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3306/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "MYSQL_ROOT_PASSWORD=dev",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "MYSQL_MAJOR=5.6",
            "MYSQL_VERSION=5.6.28-1debian8"
        ],
        "Cmd": [
            "mysqld"
        ],
        "Image": "mysql:5.6",
        "Volumes": {
            "/var/lib/mysql": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {}
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "65c2dcb4f7be53a68b972b6585fed4e6b1877b8886d08e1062101d0bd4006631",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/65c2dcb4f7be",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "4584e1d0ad5924cbe464fadf02bba01791525ed9e88fa920dd1088ecdf8f6478",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:03",
        "Networks": {
            "bridge": {
                "EndpointID": "4584e1d0ad5924cbe464fadf02bba01791525ed9e88fa920dd1088ecdf8f6478",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:03"
            }
        }
    }
}
]
```

With `2.4.1`, deleted container then ran recipe:

1st run:

```
[
{
    "Id": "cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249",
    "Created": "2016-01-20T18:30:40.869452883Z",
    "Path": "/entrypoint.sh",
    "Args": [
        "mysqld"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 6730,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-01-20T18:30:41.018801283Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7",
    "ResolvConfPath": "/docker/containers/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/resolv.conf",
    "HostnamePath": "/docker/containers/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/hostname",
    "HostsPath": "/docker/containers/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/hosts",
    "LogPath": "/docker/containers/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249-json.log",
    "Name": "/mysql",
    "RestartCount": 0,
    "Driver": "overlay",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": -1,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": null,
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "always",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {
                "max-file": "10",
                "max-size": "5m"
            }
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "overlay",
        "Data": {
            "LowerDir": "/docker/overlay/402bbbe561f0d1d325e85212880c99e6114face3b9947b133c0281fd11e1dfe7/root",
            "MergedDir": "/docker/overlay/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/merged",
            "UpperDir": "/docker/overlay/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/upper",
            "WorkDir": "/docker/overlay/cb5f299f5858205590f4c8d0955da2521a95c57264253c093e0e9d55e07be249/work"
        }
    },
    "Mounts": [
        {
            "Name": "809b9df818e0051539ad2c42298f667103894e63bf8f76333b5ebd35753d8135",
            "Source": "/docker/volumes/809b9df818e0051539ad2c42298f667103894e63bf8f76333b5ebd35753d8135/_data",
            "Destination": "/docker_mount/mysql:/etc/mysql/conf.d",
            "Driver": "local",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "23099613f4fbf62c7084f97105343c1c2a7a0933c103ac155572f9f5f310b96a",
            "Source": "/docker/volumes/23099613f4fbf62c7084f97105343c1c2a7a0933c103ac155572f9f5f310b96a/_data",
            "Destination": "/var/lib/mysql",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "cb5f299f5858",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "3306/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "MYSQL_ROOT_PASSWORD=dev",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "MYSQL_MAJOR=5.6",
            "MYSQL_VERSION=5.6.28-1debian8"
        ],
        "Cmd": [
            "mysqld"
        ],
        "Image": "mysql:5.6",
        "Volumes": {
            "/docker_mount/mysql:/etc/mysql/conf.d": {},
            "/var/lib/mysql": {}
        },
        "WorkingDir": "",
        "Entrypoint": [
            "/entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {}
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "5ec7405d58b2c9beec720c64df4ad9b2f49016ee2d0bf4ae0129c86020ac271a",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "3306/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "3306"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/5ec7405d58b2",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "33ff1d53aa78c3866838305d91e1abfe159cd9e67036382d6756ecb3e4e608ca",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.3",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:03",
        "Networks": {
            "bridge": {
                "EndpointID": "33ff1d53aa78c3866838305d91e1abfe159cd9e67036382d6756ecb3e4e608ca",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.3",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:03"
            }
        }
    }
}
]
```

2nd run is the same thing (worked as intended, container was not redeployed).

**Comment by chasebolt** [comment] 2016-01-20 18:35
oh i see! your image has a VOLUME command specified.

`{"/docker_mount/mysql:/etc/mysql/conf.d"=>{}}` <-- this is completely invalid and is a bug with how we previously handled volumes and binds. https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/

when you container is created, we are passing volumes nil (since all of your settings are parsed to go into binds). but your image has a VOLUME command in it which sets it to `/var/lib/mysql`. On the second run we see that your container volume != chef and redeploy it.

https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_base.rb#L25-L29 we use this to try and get around the issue of the Dockerfile setting also setting up the config, but this doesn't work for the nil case.

An easy hack for the time being is to set `/var/lib/mysql` in your binds/volumes so we don't continue trying to clobber it.

**Comment by scalp42** [comment] 2016-01-20 18:39
What would be the volume for `/var/lib/mysql` in that case ? Right now it's using the container itself so I'm confused.

**Comment by chasebolt** [comment] 2016-01-20 18:51
binds is similar to using mount. it will mount the host directory into the container.

volumes works as a copy. it will copy the data at `/var/lib/mysql` on the host into a new volume and then mount that inside the container.

https://docs.docker.com/engine/userguide/dockervolumes/

Binds – A list of volume bindings for this container. Each volume binding is a string in one of these forms:
`container_path `to create a new volume for the container
`host_path:container_path` to bind-mount a host path into the container
`host_path:container_path:ro` to make the bind-mount read-only inside the container.

**Comment by scalp42** [comment] 2016-01-21 00:43
Do you happen to know what would be the volume in that case on the recipe side ?

```ruby
docker_container 'mysql' do
  tag '5.6'
  port '3306:3306'
  network_mode 'bridge'
  restart_policy 'always'
  env 'MYSQL_ROOT_PASSWORD=dev'
  volumes ['/docker_mount/mysql:/etc/mysql/conf.d']
  action [:create, :run]
  end
end
```

**Comment by chasebolt** [comment] 2016-01-21 01:06
```ruby
docker_container 'mysql' do
  tag '5.6'
  port '3306:3306'
  network_mode 'bridge'
  restart_policy 'always'
  env 'MYSQL_ROOT_PASSWORD=dev'
  volumes ['/var/lib/mysql', '/docker_mount/mysql:/etc/mysql/conf.d']
  action [:create, :run]
  end
end
```

**Comment by someara** [comment] 2016-02-18 14:30
checking in... is this still an issue with 2.5.x?
Is this isolated to the log_driver and log_opt properties?

**Comment by jperville** [comment] 2016-02-18 14:39
Hi @someara this is probably still an issue but have to try again (I have since then reconfigured my docker daemon to run with log-driver=json-file and override log-driver and log-opts on a per-container basis).

The problem with the log-opt option is that it is very coupled to the current log-driver, and when using a different log-driver (such as json-file) which does not have specific log-opts then log-opts from the docker daemon are inherited (and are incorrect, hence redeploy of the container). I don't have very good suggestions other than not using exotic log-drivers for the docker daemon.

**Comment by someara** [comment] 2016-02-18 14:42
The quick and dirty option would be to set the property as desired_state:
false, effectively turning it into a control variable like "host" or "tls"

**Comment by someara** [comment] 2016-02-18 15:10
I've set the log_driver and log_opts to desired_state: false in 2.5.2.
Closing this issue. Let me know if it crops up again.

**Comment by jperville** [comment] 2016-02-18 15:10
Thank you very much @someara

**Closed by someara** 2016-02-18 15:10 UTC
Labels: bug

**Comment by KnutAtteslander** [comment] 2020-03-10 14:26
I've also run into this issue:
```
Recipe: wms-vecteur::elastic
  * docker_image[elasticsearch] action pull (up to date)
  * sysctl[vm.max_map_count] action apply (up to date)
  * docker_container[elastic] action run
    - stopping elastic
    - deleting elastic
    - update elastic
    -   set ipc_mode    to "" (was "shareable")
    -   set memory_swap to 0 (was -1)
    -   set working_dir to "" (was "/usr/share/elasticsearch")
    - starting elastic
Recipe: wms-vecteur::mariadb
  * docker_image[mariadb] action pull (up to date)
  * docker_container[mariadb] action run
    - stopping mariadb
    - deleting mariadb
    - update mariadb
    -   set ipc_mode    to "" (was "shareable")
    -   set memory_swap to 0 (was -1)
    - starting mariadb
```

receipt:
```
docker_image 'mariadb' do
  tag '10.1'
end

docker_container 'mariadb' do
  restart_policy 'always'
  tag '10.1'
  memory '2g'
  env [
    'MYSQL_ROOT_PASSWORD=kitodo',
    'MYSQL_DATABASE=kitodo',
    'MYSQL_USER=kitodo',
    'MYSQL_PASSWORD=kitodo'
  ]
  port    '3306'
  volumes ['/apps/mariadb:/var/lib/mysql']
end
```
