### ISSUE TITLE
memory_swap not idempotent

### ISSUE THREAD

**Issue by AVVS** [chef-cookbooks/docker#833] opened 2017-03-18 20:03 UTC
### Cookbook version
2.15.2

### Chef-client version
12.10.24

### Platform Details
Ubuntu 16.x

### Scenario:
docker_container resource with :run action would recreate container each time if there is a memory_swap setting. It would say "current: -1, changing to <specified_limit>" on each chef run

**Comment by iennae** [comment] 2017-03-31 20:08
We believe this is a bug. We need to do more investigation to determine for sure. Thanks for reporting this issue.

**Comment by someara** [comment] 2017-04-20 03:35
hello! fixed up in 6105c9236a98467f31380b9a26c703b74c407446
released in v2.15.5

**Comment by AVVS** [comment] 2017-04-23 22:03
Hi @someara, I dont know where this bug originates, but this did not really fix anything for me. Here is the debug output and relevant configuration:

```sh
  * docker_container[redacted-process] action run
    - stopping redacted-process  (will kill after 5s)
    - deleting redacted-process
    - update redacted-process
    -   set memory_swap to 402653184 (was -1)
    - starting redacted-process
  * execute[reload files & processor] action nothing (skipped due to action :nothing)

Running handlers:
Running handlers complete
Chef Client finished, 10/89 resources updated in 05 seconds
root@ms-files-staging-0:/var/lib/ms-files/configs# sudo docker -v
Docker version 17.04.0-ce, build 4845c56
root@ms-files-staging-0:/var/lib/ms-files/configs# docker inspect -f '{{ .HostConfig.Memory }}' redacted-process
268435456
root@ms-files-staging-0:/var/lib/ms-files/configs# docker inspect -f '{{ .HostConfig.MemorySwap }}' redacted-process
-1
root@ms-files-staging-0:/var/lib/ms-files/configs# docker inspect -f '{{ .HostConfig.MemorySwappiness }}' redacted-process
1
```

```rb
docker_container 'redacted-process' do
  repo 'gcr.io/<redacted>/redacted-process'
  tag node[:redacted_core][:redacted_process][:version]
  host_name node['hostname']
  volumes [
    "#{node['ms-files'][:data_dir]}:/configs"
  ]
  env %w(
    NODE_ENV=production
    NCONF_FILE_PATH=["/configs/redacted-process.js"]
    REDACTED_PROCESS__DEBUG=true
  )
  log_opts node['docker']['log_opts']
  command 'node ./bin/service.js'
  kill_after 5
  restart_policy 'always'
  action :run
  memory '256m' # 256 MB
  memory_swap '384m' # 256 + 128
  memory_swappiness '1'
end
```

**Comment by someara** [comment] 2017-05-01 20:33
I can't reproduce this... I exercised the resource in the test recipe basically the same way:

https://github.com/chef-cookbooks/docker/blob/ba5663adddccb22eb800ba7d0dacbbe11f77f0f4/test/cookbooks/docker_test/recipes/container.rb#L1100

Then
https://github.com/chef-cookbooks/docker/blob/ba5663adddccb22eb800ba7d0dacbbe11f77f0f4/test/integration/resources-17040/inspec/assert_functioning_spec.rb#L920-L923

Are you sure you pulled in the updated cookbook version?

-s

**Comment by AVVS** [comment] 2017-05-01 20:44
@someara yeah, pretty sure:

```sh
ubuntu@ms-files-staging-0:~$ sudo chef-client
Starting Chef Client, version 13.0.118
resolving cookbooks for run list: ["<redacted>-core::ms-files"]
Synchronizing Cookbooks:
  - redacted-docker (0.4.0)
  - docker (2.15.5) <<<<
  - chef-vault (2.1.1)
  - chef-sugar (3.4.0)
  - cappasity-core (0.6.0)
  - chef-apt-docker (1.0.0)
  - compat_resource (12.19.0)
  - sysctl (0.8.1)
  - cron (4.1.1)
  - ohai (5.0.4)
Installing Cookbook Gems:
```

Could it be a problem with underlaying docker configuration? Basically what it does is tries to set swap limit, but its at -1 after that:

```sh
root@ms-files-staging-0:/var/lib/ms-files/configs# docker inspect -f '{{ .HostConfig.MemorySwap }}' redacted-process
-1
```

So on every next run it sees that remorted swap limit is not the same as in the configuration and recreates it


```sh
  * docker_container[<redacted>-process] action run
    - stopping redacted-process  (will kill after 5s)
    - deleting redacted-process
    - update redacted-process
    -   set memory_swap to 402653184 (was -1)
    - starting redacted-process

root@ms-files-staging-0:/home/ubuntu# docker -v
Docker version 17.04.0-ce, build 4845c56
```

**Comment by someara** [comment] 2017-05-01 21:02
I suppose it could be... the `docker_service` used in the tests runs with default configs.
Are you running the stock ubuntu kernel?
-s

**Comment by AVVS** [comment] 2017-05-01 21:15
4.8.0-45-generic ubuntu 16.04 on GCE, so yeah, pretty standard

and configuration for docker service is here:

```rb
docker_service_manager 'default' do
  host ['unix:///var/run/docker.sock', "tcp://#{node[:ipaddress]}:2376"]
  tls_verify true

  # Apply tls options
  node['docker']['tls_options'].each do |opt|
    self.send opt, "/etc/docker/#{opt}.pem"
  end

  storage_driver node['docker']['storage_driver']
  graph node['docker']['data_dir']

  bip "#{node[:docker][:bip]}/16"
  dns [node[:docker][:bip]]
  dns_search ['service.consul', "c.#{node[:google_project]}.internal", 'google.internal']

  action :start
end
```

**Comment by antima-gupta** [comment] 2020-06-11 04:31
@AVVS It has fixed [here](https://github.com/chef-cookbooks/docker/pull/1112/commits/2419ea0e612864d7336520198a5ca0f7145bd8b9).
Could you please check it on the latest version of docker cookbook?

**Closed** 2020-06-11 05:07 UTC
Labels: Status: Sustaining Backlog, Type: Bug
