### ISSUE TITLE
docker_image :build_if_missing - Docker::Error::TimeoutError read timeout reached

### ISSUE THREAD

**Issue by kkeane** [chef-cookbooks/docker#458] opened 2015-09-26 23:20 UTC
This issue is similar to #403, but for the build_if_missing (and presumably build) action. I confirmed that the timeout works as expected for build_if_missing if the timeout is due to pulling a FROM image, but not when the timeout occurs during a RUN or other dockerfile entry.

In the following sample, if the image centos:latest was missing, the timeout occurred after approximately 2100 seconds (total chef runtime). If the image centos already existed, the timeout occurred after approximately 160 seconds (again total chef runtime).

    docker_image("redacted") do
      action [:build_if_missing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_image
      cookbook_name "redacted"
      tag "latest"
      source "redacted"
      force true
      read_timeout 3600
      write_timeout 3600
      repo "redacted"
      rm true
    end

Dockerfile:

FROM centos

COPY $LOCAL_DIR/*.rpm /tmp/

WORKDIR /tmp/

RUN \
   curl -SL https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -o epel.rpm \
   && yum install -y epel.rpm \
   && rm epel.rpm \
   && yum install -y \
          <about 20 local RPMs with about 100 dependencies redacted>\
          supervisor \
   && yum clean all \
   && rm -rf /usr/share/man /etc/httpd/conf.d/ssl.conf

COPY supervisord.conf /etc/supervisord.d/supervisord.ini

COPY *.cfg /etc/redacted/

COPY entrypoint.sh /

RUN \
    chown root:root /entrypoint.sh \
 && chmod u+x /entrypoint.sh

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf" ]
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR redacted
EXPOSE 80 443

**Comment by someara** [comment] 2015-09-29 14:11
I can't reproduce this... can you submit a PR with a test recipe in it that should work, but does not?

https://github.com/bflad/chef-docker/tree/2549dd4386c24ee01387a656dc14611805daf979/test/cookbooks/docker_test/recipes

Thanks

-s

**Comment by kkeane** [comment] 2015-09-29 22:35
Working on it. It appears that this only happens under certain circumstances that I haven't fully identified yet. When I whipped up a test recipe that *should* reproduce it, it didn't, but in my production cookbooks, the problem happens reliably every time (except when the Docker caching hits and speeds up the build). I would not rule out that it might be related to using chef-server for my production cookbook, but chef-zero for my test.

**Comment by kkeane** [comment] 2015-09-29 23:05
OK - I think I have it. Contrary to my original suspicion, :build seems to be working fine, but :build_if_missing exhibits the problem, even with chef-zero. There also seems to be a second condition at work that I'm still working on. Working on stripping down my test case as much as possible, and then converting it to be used in the test harness.

**Comment by kkeane** [comment] 2015-09-29 23:11
Bingo. The second condition is that the docker build process must not produce any output at all for several minutes. I haven't converted it to a test case for you yet, but here are the cookbook and Dockerfile that produces the problem. The docker file actually has three different ways of generating a long delay. One of them produces output every 10 seconds, and does not trigger the problem. The same one producing output every 5 minutes does, and the third one comes from my real-life scenario and may or may not trigger the problem depending on your network.

The recipe:
------------------------------------------------
# Test recipe to demonstrate timeout during
# docker action build_if_missing

docker_image "timeouttest" do
  action :build_if_missing
  read_timeout 3600
  write_timeout 3600
  tag    "chef"
  source "/home/kkeane/docker_bug_test/context"
end


The Dockerfile:
--------------------------------------------------------
# Create a docker image that takes a long time to build

# Centos as a base image. Any should work for the for loop test, but
# CentOS is needed for the yum test.
# Note that pulling the base image will not trigger a
# timeout, regardless of how long it
# takes
FROM centos

# Simply wait for wait for 30 minutes, output a status update every 10 seconds
# This does not appear to trigger the timeout problem
# RUN [ "bash", "-c", "for minute in {1..30} ; do for second in {0..59..10} ; do echo -n \" $minute:$second \" ; sleep 10 ; done ; done" ]

# This triggers the timeout.
RUN [ "bash", "-c", "for minute in {1..30..5} ; do echo -n \" $minute \" ; sleep 300 ; done" ]

# This should trigger the timeout unless you have a very fast Internet connection.
# RUN \
   # curl -SL https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -o epel.rpm \
   # && yum install -y epel.rpm \
   # && rm epel.rpm \
   # && yum install -y \
          # zarafa \
          # supervisor \
   # && yum clean all \
   # && rm -rf /usr/share/man /etc/httpd/conf.d/ssl.conf

**Comment by someara** [comment] 2015-09-29 23:22
Can you build your Dockerfile from the CLI?
Anything interesting in docker logs?

-s

**Comment by kkeane** [comment] 2015-09-29 23:43
Yes, the exact same Dockerfile from the CLI works without a problem - in fact, that had actually been my workaround for this problem for a while. One interesting thing in the docker log: the client disconnected after 61 seconds, although I had expected 120 seconds.

time="2015-09-29T16:03:42.353102941-07:00" level=info msg="GET /v1.16/images/timeouttest:chef/json" 
time="2015-09-29T16:03:42.354076386-07:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: timeouttest:chef" 
time="2015-09-29T16:03:42.354117732-07:00" level=error msg="HTTP Error" err="No such image: timeouttest:chef" statusCode=404 
time="2015-09-29T16:03:42.355240358-07:00" level=info msg="GET /v1.16/images/timeouttest:chef/json" 
time="2015-09-29T16:03:42.355445481-07:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: timeouttest:chef" 
time="2015-09-29T16:03:42.355469646-07:00" level=error msg="HTTP Error" err="No such image: timeouttest:chef" statusCode=404 
time="2015-09-29T16:03:42.356390431-07:00" level=info msg="GET /v1.16/images/timeouttest:chef/json" 
time="2015-09-29T16:03:42.356580259-07:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: timeouttest:chef" 
time="2015-09-29T16:03:42.356603796-07:00" level=error msg="HTTP Error" err="No such image: timeouttest:chef" statusCode=404 
time="2015-09-29T16:03:42.357486797-07:00" level=info msg="GET /v1.16/images/timeouttest:chef/json" 
time="2015-09-29T16:03:42.357667057-07:00" level=error msg="Handler for GET /images/{name:.*}/json returned error: No such image: timeouttest:chef" 
time="2015-09-29T16:03:42.357690384-07:00" level=error msg="HTTP Error" err="No such image: timeouttest:chef" statusCode=404 
time="2015-09-29T16:03:42.361159318-07:00" level=info msg="POST /v1.16/build?nocache=false&rm=true" 
time="2015-09-29T16:04:43.800775146-07:00" level=info msg="Client disconnected, cancelling job: build"

**Comment by danfromtitan** [comment] 2015-10-02 17:34
Having the same issue.

**Comment by someara** [comment] 2015-10-03 18:52
We now have a test case for this! (thanks Kevin)

https://github.com/bflad/chef-docker/blob/69333d40e96669ca68d6b9c3bdcc884ce65de67e/test/cookbooks/docker_test/recipes/timeout.rb

Indeed, it seems that the timeout isn't being honored. I believe this is because everything shares the same Docker.connection, and the solution is going to be a connection per resource. So, Fixing this means also solving #322. (I hope)

**Comment by chasebolt** [comment] 2015-10-06 08:24
this one is a bugger to figure out. pr #483 corrects connection sharing per resource and debug shows the read_timeout is set properly in Docker.connection. Yet this test-kitchen case keeps failing at the 10 minute mark consistently. Here is a chef dump from test-kitchen with my per-resource connection change.

https://gist.github.com/chasebolt/5f68e302377a2597067a

**Comment by kkeane** [comment] 2015-10-06 19:45
Interesting observation that it fails consistently after 10 minutes. For me, it consistently fails after either one or two minutes, so something must have changed.

I've been looking at various places in the Docker-API and Excon gems. No smoking gun :-( Obviously, the method timeout_reached in Excon's socket.rb sees the wrong value, and as you found out, Docker.connection still has the correct value.

What I notice is that the options are copied around an awful lot of times and in fairly complex ways before they end up at the socket level. Any one of these copy operations could somehow either miss the timeout values, or clobber them with the defaults.

Between those boundaries, as far as I can tell, the following interesting things happen:

docker/connection.rb line 32: Excon constructor is called (options are passed in from Docker connection)
line 40: Excon connection request is made (request params are passed in from Docker connection)

excon/connection.rb line 59: parameters are merged in in the constructor
line 206: parameters are merged in
line 233: parameters are passed on to the middlewares

excon/socket.rb line 24: data is simply set, not merged.
line 291: this is where apparently the wrong timeout value is used.

There could be additional places, but these seem like the prime suspect to me.
 
-----Original message-----

**Comment by chasebolt** [comment] 2015-10-06 19:50
I did a lot of changes moving to Docker::Connection which has made it consistently fail at the 10 minute mark now. Not sure why I can't get past that time length though.

I'll do some dumping of Excon and verify if it matches with Docker.connection or not.

**Comment by phanikumar1210** [comment] 2015-12-06 11:32
I am also facing the same issue when I tried to pull down saisasank001/sasank from docker hub. Can anyone please suggest me on how resolve my issue.

**Comment by danfromtitan** [comment] 2015-12-07 15:07
A possible workaround is to refactor your code to avoid the use of build_if_missing action (at least until excon gets fixed).

**Comment by phanikumar1210** [comment] 2015-12-07 15:16
Hi,

Thanks for your response but I haven't used build if missing. Please find
the below recipe for reference

docker_image 'saisasank001/iib' do
  action :pull
end
docker_container 'server' do
  repo 'saisasank001/iib'
  port '4414:4414'
end

Thank you.

On Mon, Dec 7, 2015 at 8:37 PM, danfromtitan <notifications@github.com>
wrote:

> A possible workaround is to refactor your code to avoid the use of
> build_if_missing action (at least until excon gets fixed).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef-cookbooks/docker/issues/458#issuecomment-162550689>
> .
>



-- 
*With Regards,*
*T.V.R.L.PhaniKumar Dadi *
*E-Mail: phanikumardadi.kumar@gmail.com <phanikumardadi.kumar@gmail.com>*
*Phone: 9703905266*

**Closed** 2015-12-11 22:26 UTC
Labels: bug, Medium Priority
