### ISSUE TITLE
2.13.x fails behind proxy during docker image pull

### ISSUE THREAD

**Issue by codereflection** [chef-cookbooks/docker#799] opened 2017-01-09 18:26 UTC
### Cookbook version
2.13.x (tested 2.13.0 through 2.13.9)

### Chef-client version
12.17.44

### Platform Details
Ubuntu via test kitchen

### Scenario:
Trying to pull a docker image (Artifactory) in cookbook v2.13.x using the `docker_image` resource, works fine in <= v2.12.0. Something changed in the docker cookbook in v2.13.0 that now tries a connection to `https://jfrog-docker-reg2.bintray.io/v1/_ping` and fails due to not using the configured proxy in the docker_service resource.

### Steps to Reproduce:
1. Setup for working behind a proxy
2. Recipe to pull docker image

```ruby
docker_service 'default' do
  http_proxy 'http://myproxy:8080'
  https_proxy 'http://myproxy:8080'
  action [:create, :start]
end

docker_image 'jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro' do
  tag 'latest'
  action :pull
end
```
3. Use docker cookbook version `2.13.9`
4. Converge
5. Observe failure while connecting to `https://jfrog-docker-reg2.bintray.io/v1/_ping`

### Expected Result:
Expected recipe to successfully pull down docker image

### Actual Result:
Failure during connection to `https://jfrog-docker-reg2.bintray.io/v1/_ping`
```
       Recipe: mycompany-docker::artifactory
         * ruby_block[set as first time run] action nothing (skipped due to action :nothing)
         * docker_image[jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro] action pull

           ================================================================================
           Error executing action `pull` on resource 'docker_image[jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro]'
           ================================================================================

           Docker::Error::ServerError
           --------------------------
           Get https://jfrog-docker-reg2.bintray.io/v1/_ping: dial tcp 108.168.194.93:443: getsockopt: connection refused

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_image.rb:71:in `block in pull_image'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_base.rb:66:in `with_retries'
           /tmp/kitchen/cache/cookbooks/docker/libraries/helpers_image.rb:66:in `pull_image'
           /tmp/kitchen/cache/cookbooks/docker/libraries/docker_image.rb:61:in `block in <class:DockerImage>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mycompany-docker/recipes/artifactory.rb

            17: docker_image 'jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro' do
            18:   tag artifactory_version
            19:   action :pull
            20: end
            21:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mycompany-docker/recipes/artifactory.rb:17:in `from_file'

           docker_image("jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro") do
             action [:pull]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_image
             cookbook_name "mycompany-docker"
             recipe_name "artifactory"
             tag "latest"
             repo "jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro"
             connection #<Docker::Connection:0x0000000360a4e8 @url="unix:///", @options={:socket=>"/var/run/docker.sock", :read_timeout=>120}>
           end

           Platform:
           ---------
           x86_64-linux


       Running handlers:
       [2017-01-09T18:08:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-01-09T18:08:38+00:00] ERROR: Exception handlers complete
       Chef Client failed. 14 resources updated in 47 seconds
       [2017-01-09T18:08:38+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-01-09T18:08:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-01-09T18:08:38+00:00] ERROR: docker_image[jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro] (mycompany-docker::artifactory line 17) had an error: Docker::Error::ServerError: Get https://jfrog-docker-reg2.bintray.io/v1/_ping: dial tcp 108.168.194.93:443: getsockopt: connection refused

       [2017-01-09T18:08:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by bkaraoglanov** [comment] 2017-01-31 07:24
I have found a bug in libraries/docker_service_manager_systemd.rb line 59

Here is a fix:
Replace that block with

`      template "/etc/systemd/system/docker.service.d/http-proxy.conf" do
        source 'systemd/docker.service-override.erb'
        owner 'root'
        group 'root'
        mode '0644'
        variables(
          config: new_resource,
          docker_daemon_cmd: docker_daemon_cmd,
          systemd_args: systemd_args,
          docker_wait_ready: "#{libexec_dir}/#{docker_name}-wait-ready",
          docker_mount_flags: mount_flags
        )
        cookbook 'docker'
        notifies :run, 'execute[systemctl daemon-reload]', :immediately
        action :create
      end`

**Comment by someara** [comment] 2017-02-15 09:21
Hi. 

I can't reproduce this..

I've put a proxy in the chain in the smoke testing suite here:

https://github.com/chef-cookbooks/docker/blob/master/test/cookbooks/docker_test/recipes/smoke.rb#L66-L72

Works across all platforms / service managers.

Is this still an issue in 2.14.x?

-s

**Comment by bkaraoglanov** [comment] 2017-02-15 13:00
I see that is fixed but when proxies setup docker demon reloaded but no the
docker engine. In order to put docker proxy in place docker engine needs to
be restarted here is my work around:

I defined service:
      execute 'systemctl restart docker' do
        command '/bin/systemctl restart docker'
        action :nothing
      end

Than at the change of proxy:
      template "/etc/systemd/system/#{docker_name}.service" do
        source 'systemd/docker.service-override.erb'
        owner 'root'
        group 'root'
        mode '0644'
        variables(
          config: new_resource,
          docker_daemon_cmd: docker_daemon_cmd,
          systemd_args: systemd_args,
          docker_wait_ready: "#{libexec_dir}/#{docker_name}-wait-ready",
          docker_mount_flags: mount_flags
        )
        cookbook 'docker'
        notifies :run, 'execute[systemctl daemon-reload]', :immediately
  >>      notifies :run, 'execute[systemctl restart docker]', :immediately
        action :create
      end

**Comment by someara** [comment] 2017-02-15 14:24
I added a restart to the template resources in 00707bf5e0c4d2d3a73dfc41cebc7053157cd6fd
Released in v2.15.1

**Comment by someara** [comment] 2017-02-15 14:38
Reverted that change... broke the build

https://travis-ci.org/chef-cookbooks/docker/builds/201882788

**Comment by bkaraoglanov** [comment] 2017-02-15 20:36
How can I contribute to a project ?

**Comment by someara** [comment] 2017-02-16 13:16
https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

**Comment by chasebolt** [comment] 2017-08-07 17:35
this should be resolved in the latest release. please reopen if the issue still persists.

**Closed by chasebolt** 2017-08-07 17:35 UTC
Labels: Type: Bug
