### ISSUE TITLE
Installing CE version through package.

### ISSUE THREAD

**Issue by odg0318** [chef-cookbooks/docker#875] opened 2017-06-30 03:38 UTC
### Cookbook version
2.15.6

### Chef-client version
12.18.31

### Platform Details
Opsworks Chef12, Ubuntu 16.04

### Scenario:
1. Version is specified to 17.03.1 and `install_method` to `package`
2. It is expected to install `docker-ce` package.
3. This error message  is shown; `No candidate version available for docker-engine`

### Steps to Reproduce:
skip

### Expected Result:
I expect that docker cookbook install docker package using `docker-ce` package not `docker-engine`.

### Actual Result:
docker cookbook tried to install using `docker-engine` cookbook.

**Comment by iennae** [comment] 2017-06-30 13:21
This is a duplicate of Issue #874. Closing this in favor of the earlier filed issue.

**Closed by iennae** 2017-06-30 13:21 UTC

**Comment by odg0318** [comment] 2017-07-03 01:12
I don't thinks that this is duplicated with #874 which is related to AWS Amazon.
There is no method to install docker repository in cookbook when I try to install through package.

What do you think of adding a feature to install docker repository?

**Comment by chasebolt** [comment] 2017-07-04 02:55
If I recall correctly, docker-engine is docker-ce. The docker repository
that is currently used when using packages is their older repository before
docker-ce and docker-ee. But the repository, while named docker-engine, is
actually docker-ce.

Currently the cookbook does not support docker-ee; but that is a separate
issue.

**Comment by odg0318** [comment] 2017-07-04 05:44
I don't know that docker in older repository is docker-ce.
But I think new repository is required someday.

Thanks!

**Comment by someara** [comment] 2017-07-04 15:50
hello! 

Just dropping a note in this thread for clarification.

The docker_installation_package resource does install the ce packages by default

https://github.com/chef-cookbooks/docker/blob/c364127e37762596796d10c88631bfc2bf2e2204/libraries/helpers_installation_package.rb#L72

Enabling the repositories, however, is out of scope for this cookbook (this is a pure library cookbook, and therefore has no recipes.)

If you take a look at the test-kitchen harness... you'll see it using the `chef-apt-docker` and `chef-yum-docker cookbooks` where appropriate.

https://github.com/chef-cookbooks/docker/blob/c364127e37762596796d10c88631bfc2bf2e2204/.kitchen.yml#L77

This is enabled as a loose (testing) dependency via Berkshelf

https://github.com/chef-cookbooks/docker/blob/c364127e37762596796d10c88631bfc2bf2e2204/Berksfile

Hope that helps!

-s

**Comment by odg0318** [comment] 2017-07-04 23:25
@someara Many thanks! It makes me clarified much.

**Comment by odg0318** [comment] 2017-07-04 23:39
I am still stuck into some problem.
I created new EC2 machine which OS is Ubuntu 16.04 to see default docker package.
After updating package list via `apt update`, I checked `docker` version list.

> $ apt-cache madison docker
    docker |      1.5-1 | http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
    docker |      1.5-1 | http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial/universe Sources

How can I show `docker` latest version in my respositories?

**Comment by someara** [comment] 2017-07-04 23:44
Put this in your run_list https://github.com/chef-cookbooks/chef-apt-docker
