### ISSUE TITLE
docker_service_manager sometimes broken on ubuntu-14.04

### ISSUE THREAD

**Issue by frezbo** [chef-cookbooks/docker#823] opened 2017-02-14 16:59 UTC
### Cookbook version
2.14.4

### Chef-client version
12.9

### Platform Details
Ubuntu 14.04

### Scenario:
issue with docker on ubuntu

**Comment by someara** [comment] 2017-02-15 09:19
I can't reproduce this

Converged the smoke-ubuntu-1404 suite twice.
Then logged in and tried to do a `service docker start` while it was already running.
No errors.

https://gist.github.com/someara/3a0bb917c818a6acdb0c52c8e3c4d9bc

**Comment by frezbo** [comment] 2017-02-15 10:20
Hi, thanks for the reply. The issue is not  I mentioned, I think it has to do with the latest build failures. I will rerun chef-client with verbose mode and I may be able to provide more light into the issue

**Comment by frezbo** [comment] 2017-02-15 10:24
```
2017-02-15T10:22:26+00:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.17.44
[2017-02-15T10:22:28+00:00] WARN: Run List override has been provided.
[2017-02-15T10:22:28+00:00] WARN: Original Run List: []
[2017-02-15T10:22:28+00:00] WARN: Overridden Run List: [recipe[test]]
resolving cookbooks for run list: ["test"]
Synchronizing Cookbooks:
  - test (0.1.0)
  - ssh_keygen (1.1.0)
  - ssl_certificate (2.1.0)
  - s3_file (2.7.0)
  - ark (2.2.1)
  - docker (2.14.3)
  - poise (2.7.2)
  - build-essential (7.0.3)
  - windows (2.1.1)
  - seven_zip (2.0.2)
  - mingw (1.2.5)
  - compat_resource (12.16.3)
  - ohai (4.2.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 3 resources
Recipe: test::docker
  * docker_service[start service] action restart
    * docker_service_manager_upstart[start service] action restart
      * service[docker-start service] action stop (up to date)
      * directory[/usr/lib/docker] action create (up to date)
      * template[/usr/lib/docker/docker-start service-wait-ready] action create (up to date)
      * link[/usr/bin/dockerd-start service] action create (up to date)
      * template[/etc/init/docker-start service.conf] action create (up to date)
      * template[/etc/default/docker-start service] action create (up to date)
      * service[docker-start service] action start
        
        ================================================================================
        Error executing action `start` on resource 'service[docker-start service]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /sbin/start docker-start service ----
        STDOUT: 
        STDERR: start: Unknown job: docker-start
        ---- End output of /sbin/start docker-start service ----
        Ran /sbin/start docker-start service returned 1
        
        Cookbook Trace:
        ---------------
        /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
        
        Resource Declaration:
        ---------------------
        # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb
        
         43:       service docker_name do
         44:         provider Chef::Provider::Service::Upstart
         45:         supports status: true
         46:         action :start
         47:       end
         48:     end
        
        Compiled Resource:
        ------------------
        # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:43:in `block in <class:DockerServiceManagerUpstart>'
        
        service("docker-start service") do
          provider Chef::Provider::Service::Upstart
          action [:start]
          supports {:status=>true}
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          service_name "docker-start service"
          pattern "docker-start service"
          declared_type :service
          cookbook_name "test"
        end
        
        Platform:
        ---------
        x86_64-linux
        
      
      ================================================================================
      Error executing action `restart` on resource 'docker_service_manager_upstart[start service]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
      ---- Begin output of /sbin/start docker-start service ----
      STDOUT: 
      STDERR: start: Unknown job: docker-start
      ---- End output of /sbin/start docker-start service ----
      Ran /sbin/start docker-start service returned 1
      
      Cookbook Trace:
      ---------------
      /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
      
      Resource Declaration:
      ---------------------
      # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb
      
       77:           svc = docker_service_manager(name, &block)
       78:         when 'execute'
       79:           svc = docker_service_manager_execute(name, &block)
       80:         when 'sysvinit'
       81:           svc = docker_service_manager_sysvinit(name, &block)
       82:         when 'upstart'
       83:           svc = docker_service_manager_upstart(name, &block)
       84:         when 'systemd'
       85:           svc = docker_service_manager_systemd(name, &block)
       86:         end
       87:         copy_properties_to(svc)
       88:         svc
       89:       end
       90:     end
       91: 
       92:     #########
       93:     # Actions
       94:     #########
       95: 
       96:     action :create do
       97:       validate_install_method
       98: 
       99:       installation do
      100:         action :create
      101:         notifies :restart, new_resource, :immediately
      102:       end
      103:     end
      104: 
      105:     action :delete do
      106:       installation do
      107:         action :delete
      108:       end
      109:     end
      110: 
      111:     action :start do
      112:       svc_manager do
      113:         action :start
      114:       end
      115:     end
      116: 
      117:     action :stop do
      118:       svc_manager do
      119:         action :stop
      120:       end
      121:     end
      122: 
      123:     action :restart do
      124:       svc_manager do
      125:         action :restart
      126:       end
      127:     end
      128:   end
      129: end
      
      Compiled Resource:
      ------------------
      # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb:77:in `svc_manager'
      
      docker_service_manager_upstart("start service") do
        action [:restart]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "test"
        pidfile "/var/run/docker-start service.pid"
      end
      
      Platform:
      ---------
      x86_64-linux
      
    
    ================================================================================
    Error executing action `restart` on resource 'docker_service[start service]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    docker_service_manager_upstart[start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start docker-start service ----
    STDOUT: 
    STDERR: start: Unknown job: docker-start
    ---- End output of /sbin/start docker-start service ----
    Ran /sbin/start docker-start service returned 1
    
    Cookbook Trace:
    ---------------
    /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
    
    Resource Declaration:
    ---------------------
    # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/test/recipes/docker.rb
    
      1: docker_service 'start service' do
      2: 	action [:restart]
      3: end
      4: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/test/recipes/docker.rb:1:in `from_file'
    
    docker_service("start service") do
      action [:restart]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_service
      cookbook_name "test"
      recipe_name "docker"
      service_manager "auto"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2017-02-15T10:22:33+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-02-15T10:22:33+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 06 seconds
[2017-02-15T10:22:33+00:00] FATAL: Stacktrace dumped to /home/vagrant/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-02-15T10:22:33+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-02-15T10:22:33+00:00] ERROR: docker_service[start service] (test::docker line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_upstart[start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start docker-start service ----
STDOUT: 
STDERR: start: Unknown job: docker-start
---- End output of /sbin/start docker-start service ----
Ran /sbin/start docker-start service returned 1
[2017-02-15T10:22:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
This is the error

**Comment by someara** [comment] 2017-02-15 10:47
I've just released 2.15.0, which removes the dependency on compat_resource... which has historically caused a lot of hard-to-track-down weirdness.

Can you test against that real quick?

-s

**Comment by frezbo** [comment] 2017-02-15 10:54
yeh sure, just 10 mins

**Comment by frezbo** [comment] 2017-02-15 11:09
```
[2017-02-15T11:08:07+00:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.17.44
[2017-02-15T11:08:09+00:00] WARN: Run List override has been provided.
[2017-02-15T11:08:09+00:00] WARN: Original Run List: []
[2017-02-15T11:08:09+00:00] WARN: Overridden Run List: [recipe[test]]
resolving cookbooks for run list: ["test"]
Synchronizing Cookbooks:
  - s3_file (2.7.0)
  - test (0.1.0)
  - ssh_keygen (1.1.0)
  - ssl_certificate (2.1.0)
  - ark (2.2.1)
  - docker (2.15.0)
  - poise (2.7.2)
  - mingw (1.2.5)
  - seven_zip (2.0.2)
  - build-essential (8.0.0)
  - windows (2.1.1)
  - ohai (4.2.3)
  - compat_resource (12.16.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 3 resources
Recipe: test::docker
  * docker_service[start service] action create
    * docker_installation_script[start service] action create
      * apt_package[curl] action install (up to date)
      * execute[install docker] action run (up to date)
       (up to date)
     (up to date)
  * docker_service[start service] action start
    * docker_service_manager_upstart[start service] action start
      * directory[/usr/lib/docker] action create (up to date)
      * template[/usr/lib/docker/docker-start service-wait-ready] action create (up to date)
      * link[/usr/bin/dockerd-start service] action create (up to date)
      * template[/etc/init/docker-start service.conf] action create (up to date)
      * template[/etc/default/docker-start service] action create (up to date)
      * service[docker-start service] action start
        
        ================================================================================
        Error executing action `start` on resource 'service[docker-start service]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /sbin/start docker-start service ----
        STDOUT: 
        STDERR: start: Unknown job: docker-start
        ---- End output of /sbin/start docker-start service ----
        Ran /sbin/start docker-start service returned 1
        
        Resource Declaration:
        ---------------------
        # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb
        
         43:       service docker_name do
         44:         provider Chef::Provider::Service::Upstart
         45:         supports status: true
         46:         action :start
         47:       end
         48:     end
        
        Compiled Resource:
        ------------------
        # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:43:in `block in <class:DockerServiceManagerUpstart>'
        
        service("docker-start service") do
          provider Chef::Provider::Service::Upstart
          action [:start]
          supports {:status=>true}
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          service_name "docker-start service"
          pattern "docker-start service"
          declared_type :service
          cookbook_name "test"
        end
        
        Platform:
        ---------
        x86_64-linux
        
      
      ================================================================================
      Error executing action `start` on resource 'docker_service_manager_upstart[start service]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
      ---- Begin output of /sbin/start docker-start service ----
      STDOUT: 
      STDERR: start: Unknown job: docker-start
      ---- End output of /sbin/start docker-start service ----
      Ran /sbin/start docker-start service returned 1
      
      Resource Declaration:
      ---------------------
      # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb
      
       77:           svc = docker_service_manager(name, &block)
       78:         when 'execute'
       79:           svc = docker_service_manager_execute(name, &block)
       80:         when 'sysvinit'
       81:           svc = docker_service_manager_sysvinit(name, &block)
       82:         when 'upstart'
       83:           svc = docker_service_manager_upstart(name, &block)
       84:         when 'systemd'
       85:           svc = docker_service_manager_systemd(name, &block)
       86:         end
       87:         copy_properties_to(svc)
       88:         svc
       89:       end
       90:     end
       91: 
       92:     #########
       93:     # Actions
       94:     #########
       95: 
       96:     action :create do
       97:       validate_install_method
       98: 
       99:       installation do
      100:         action :create
      101:         notifies :restart, new_resource, :immediately
      102:       end
      103:     end
      104: 
      105:     action :delete do
      106:       installation do
      107:         action :delete
      108:       end
      109:     end
      110: 
      111:     action :start do
      112:       svc_manager do
      113:         action :start
      114:       end
      115:     end
      116: 
      117:     action :stop do
      118:       svc_manager do
      119:         action :stop
      120:       end
      121:     end
      122: 
      123:     action :restart do
      124:       svc_manager do
      125:         action :restart
      126:       end
      127:     end
      128:   end
      129: end
      
      Compiled Resource:
      ------------------
      # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb:77:in `svc_manager'
      
      docker_service_manager_upstart("start service") do
        action [:start]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "test"
        pidfile "/var/run/docker-start service.pid"
      end
      
      Platform:
      ---------
      x86_64-linux
      
    
    ================================================================================
    Error executing action `start` on resource 'docker_service[start service]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    docker_service_manager_upstart[start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start docker-start service ----
    STDOUT: 
    STDERR: start: Unknown job: docker-start
    ---- End output of /sbin/start docker-start service ----
    Ran /sbin/start docker-start service returned 1
    
    Resource Declaration:
    ---------------------
    # In /home/vagrant/.chef/local-mode-cache/cache/cookbooks/test/recipes/docker.rb
    
      1: docker_service 'start service' do
      2:  action [:create, :start]
      3: end
      4: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/vagrant/.chef/local-mode-cache/cache/cookbooks/test/recipes/docker.rb:1:in `from_file'
    
    docker_service("start service") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_service
      cookbook_name "test"
      recipe_name "docker"
      install_method "auto"
      service_manager "auto"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2017-02-15T11:08:14+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-02-15T11:08:14+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 06 seconds
[2017-02-15T11:08:14+00:00] FATAL: Stacktrace dumped to /home/vagrant/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-02-15T11:08:14+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-02-15T11:08:14+00:00] ERROR: docker_service[start service] (test::docker line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_upstart[start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/vagrant/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start docker-start service ----
STDOUT: 
STDERR: start: Unknown job: docker-start
---- End output of /sbin/start docker-start service ----
Ran /sbin/start docker-start service returned 1
[2017-02-15T11:08:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
again issues with 2.15.0

**Comment by someara** [comment] 2017-02-15 11:13
Thanks!

I'll take a closer look when I get a sec

**Comment by frezbo** [comment] 2017-02-15 11:25
@someara Great, thanks, I am blocked due to this.

**Comment by frezbo** [comment] 2017-02-15 12:44
```
[2017-02-15T12:43:15+00:00] WARN: No config file found or specified on command line, using command line options.
[2017-02-15T12:43:16+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.18.31
[2017-02-15T12:43:16+00:00] INFO: *** Chef 12.18.31 ***
[2017-02-15T12:43:16+00:00] INFO: Platform: x86_64-linux
[2017-02-15T12:43:16+00:00] INFO: Chef-client pid: 14640
[2017-02-15T12:43:17+00:00] WARN: Run List override has been provided.
[2017-02-15T12:43:17+00:00] WARN: Original Run List: []
[2017-02-15T12:43:17+00:00] WARN: Overridden Run List: [recipe[docker]]
[2017-02-15T12:43:17+00:00] INFO: Run List is [recipe[docker]]
[2017-02-15T12:43:17+00:00] INFO: Run List expands to [docker]
[2017-02-15T12:43:17+00:00] INFO: Starting Chef Run for ip-10-16-1-195.ec2.internal
[2017-02-15T12:43:17+00:00] INFO: Running start handlers
[2017-02-15T12:43:17+00:00] INFO: Start handlers complete.
[2017-02-15T12:43:17+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: 
resolving cookbooks for run list: ["docker"]
[2017-02-15T12:43:18+00:00] INFO: Loading cookbooks [docker@0.1.0, ssl_certificate@2.1.0, ssh_keygen@1.1.0, s3_file@2.7.0, ark@2.2.1, docker@2.14.3, poise@2.7.2, build-essential@8.0.0, windows@2.1.1, seven_zip@2.0.2, compat_resource@12.16.3, mingw@1.2.5, ohai@4.2.3]
[2017-02-15T12:43:18+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
[2017-02-15T12:43:18+00:00] INFO: Storing updated cookbooks/docker/recipes/default.rb in the cache.
  - ssh_keygen (1.1.0)
  - docker (0.1.0)
  - ssl_certificate (2.1.0)
  - ark (2.2.1)
  - s3_file (2.7.0)
  - docker (2.14.3)
  - poise (2.7.2)
  - build-essential (8.0.0)
  - windows (2.1.1)
  - seven_zip (2.0.2)
  - mingw (1.2.5)
  - compat_resource (12.16.3)
  - ohai (4.2.3)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 17 resources
Recipe: docker::docker
  * docker_service[start service] action create[2017-02-15T12:43:18+00:00] INFO: Processing docker_service[start service] action create (docker::docker line 1)

    * docker_installation_script[start service] action create[2017-02-15T12:43:18+00:00] INFO: Processing docker_installation_script[start service] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 57)

      * apt_package[curl] action install[2017-02-15T12:43:18+00:00] INFO: Processing apt_package[curl] action install (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_installation_script.rb line 35)
 (up to date)
      * execute[install docker] action run[2017-02-15T12:43:18+00:00] INFO: Processing execute[install docker] action run (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_installation_script.rb line 39)
 (up to date)
       (up to date)
     (up to date)
  * docker_service[start service] action restart[2017-02-15T12:43:18+00:00] INFO: Processing docker_service[start service] action restart (docker::docker line 1)

    * docker_service_manager_upstart[start service] action restart[2017-02-15T12:43:18+00:00] INFO: Processing docker_service_manager_upstart[start service] action restart (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77)

      * service[docker-start service] action stop[2017-02-15T12:43:18+00:00] INFO: Processing service[docker-start service] action stop (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 51)
 (up to date)
      * directory[/usr/lib/docker] action create[2017-02-15T12:43:18+00:00] INFO: Processing directory[/usr/lib/docker] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_base.rb line 100)
 (up to date)
      * template[/usr/lib/docker/docker-start service-wait-ready] action create[2017-02-15T12:43:18+00:00] INFO: Processing template[/usr/lib/docker/docker-start service-wait-ready] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_base.rb line 107)
 (up to date)
      * link[/usr/bin/dockerd-start service] action create[2017-02-15T12:43:18+00:00] INFO: Processing link[/usr/bin/dockerd-start service] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 11)
 (up to date)
      * template[/etc/init/docker-start service.conf] action create[2017-02-15T12:43:18+00:00] INFO: Processing template[/etc/init/docker-start service.conf] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 17)
 (up to date)
      * template[/etc/default/docker-start service] action create[2017-02-15T12:43:18+00:00] INFO: Processing template[/etc/default/docker-start service] action create (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 32)
 (up to date)
      * service[docker-start service] action start[2017-02-15T12:43:18+00:00] INFO: Processing service[docker-start service] action start (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43)

        
        ================================================================================
        Error executing action `start` on resource 'service[docker-start service]'
        ================================================================================
        
        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /sbin/start docker-start service ----
        STDOUT: 
        STDERR: start: Unknown job: docker-start
        ---- End output of /sbin/start docker-start service ----
        Ran /sbin/start docker-start service returned 1
        
        Cookbook Trace:
        ---------------
        /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
        
        Resource Declaration:
        ---------------------
        # In /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb
        
         43:       service docker_name do
         44:         provider Chef::Provider::Service::Upstart
         45:         supports status: true
         46:         action :start
         47:       end
         48:     end
        
        Compiled Resource:
        ------------------
        # Declared in /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:43:in `block in <class:DockerServiceManagerUpstart>'
        
        service("docker-start service") do
          provider Chef::Provider::Service::Upstart
          action [:start]
          supports {:status=>true}
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          service_name "docker-start service"
          pattern "docker-start service"
          declared_type :service
          cookbook_name "docker"
        end
        
        Platform:
        ---------
        x86_64-linux
        
[2017-02-15T12:43:18+00:00] INFO: Running queued delayed notifications before re-raising exception
      
      ================================================================================
      Error executing action `restart` on resource 'docker_service_manager_upstart[start service]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      service[docker-start service] (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
      ---- Begin output of /sbin/start docker-start service ----
      STDOUT: 
      STDERR: start: Unknown job: docker-start
      ---- End output of /sbin/start docker-start service ----
      Ran /sbin/start docker-start service returned 1
      
      Cookbook Trace:
      ---------------
      /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
      
      Resource Declaration:
      ---------------------
      # In /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb
      
       77:           svc = docker_service_manager(name, &block)
       78:         when 'execute'
       79:           svc = docker_service_manager_execute(name, &block)
       80:         when 'sysvinit'
       81:           svc = docker_service_manager_sysvinit(name, &block)
       82:         when 'upstart'
       83:           svc = docker_service_manager_upstart(name, &block)
       84:         when 'systemd'
       85:           svc = docker_service_manager_systemd(name, &block)
       86:         end
       87:         copy_properties_to(svc)
       88:         svc
       89:       end
       90:     end
       91: 
       92:     #########
       93:     # Actions
       94:     #########
       95: 
       96:     action :create do
       97:       validate_install_method
       98: 
       99:       installation do
      100:         action :create
      101:         notifies :restart, new_resource, :immediately
      102:       end
      103:     end
      104: 
      105:     action :delete do
      106:       installation do
      107:         action :delete
      108:       end
      109:     end
      110: 
      111:     action :start do
      112:       svc_manager do
      113:         action :start
      114:       end
      115:     end
      116: 
      117:     action :stop do
      118:       svc_manager do
      119:         action :stop
      120:       end
      121:     end
      122: 
      123:     action :restart do
      124:       svc_manager do
      125:         action :restart
      126:       end
      127:     end
      128:   end
      129: end
      
      Compiled Resource:
      ------------------
      # Declared in /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb:77:in `svc_manager'
      
      docker_service_manager_upstart("start service") do
        action [:restart]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :docker_service_manager
        cookbook_name "docker"
        pidfile "/var/run/docker-start service.pid"
      end
      
      Platform:
      ---------
      x86_64-linux
      
[2017-02-15T12:43:18+00:00] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `restart` on resource 'docker_service[start service]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    docker_service_manager_upstart[start service] (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /sbin/start docker-start service ----
    STDOUT: 
    STDERR: start: Unknown job: docker-start
    ---- End output of /sbin/start docker-start service ----
    Ran /sbin/start docker-start service returned 1
    
    Cookbook Trace:
    ---------------
    /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb:60:in `block in <class:DockerServiceManagerUpstart>'
    
    Resource Declaration:
    ---------------------
    # In /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/recipes/docker.rb
    
      1: docker_service 'start service' do
      2: 	action [:create, :restart]
      3: end
      4: 
    
    Compiled Resource:
    ------------------
    # Declared in /home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/recipes/docker.rb:1:in `from_file'
    
    docker_service("start service") do
      action [:create, :restart]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :docker_service
      cookbook_name "docker"
      recipe_name "docker"
      install_method "auto"
      service_manager "auto"
    end
    
    Platform:
    ---------
    x86_64-linux
    
[2017-02-15T12:43:18+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-02-15T12:43:18+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-02-15T12:43:18+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2017-02-15T12:43:18+00:00] FATAL: Stacktrace dumped to /home/ubuntu/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-02-15T12:43:18+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-02-15T12:43:18+00:00] ERROR: docker_service[start service] (docker::docker line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: docker_service_manager_upstart[start service] (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service.rb line 77) had an error: Mixlib::ShellOut::ShellCommandFailed: service[docker-start service] (/home/ubuntu/.chef/local-mode-cache/cache/cookbooks/docker/libraries/docker_service_manager_upstart.rb line 43) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/start docker-start service ----
STDOUT: 
STDERR: start: Unknown job: docker-start
---- End output of /sbin/start docker-start service ----
Ran /sbin/start docker-start service returned 1
[2017-02-15T12:43:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
This is the output on  a new  aws ec2 14.04 instance

**Comment by frezbo** [comment] 2017-02-15 12:49
@someara I think this command is causing this issue:
```/sbin/start docker-start
start: Unknown job: docker-start
```

**Comment by someara** [comment] 2017-02-15 14:15
Aha. I see what's happening.
use:

 ```ruby
docker_service "default"
```

or

```ruby
docker_service "string_without_spaces"
```

**Comment by frezbo** [comment] 2017-02-15 14:48
@someara  I have to add this:
```
service "docker" do
    supports :status => true
    action :stop
end
``` 
before the docker_service for the cookbook to run perfectly on the second run

**Comment by frezbo** [comment] 2017-02-15 14:48
Otherwise I am okay with this.

**Comment by someara** [comment] 2017-02-15 14:56
You shouldn't have to do that. 

The whole point of the `docker_service_manager` is to be a wrapper around `service`.

It is designed to support multiple instances of a docker engine running on the same machine. 
It uses a naming scheme based on the resource name to pull this off. The name "default" is special.

The cookbook is not correctly handling the a resource `docker_service[start whatever]` because of the space in the resource name. A proper fix would enforce a regex and reject "start service" as input.

-s

**Comment by frezbo** [comment] 2017-02-15 15:32
@someara Thanks for the input, its working fine now. I willbe closing this ticket.

**Comment by frezbo** [comment] 2017-02-15 23:59
@someara  Re-opening this issue, as the cookbook run on a new machine still has issues.

**Comment by someara** [comment] 2017-02-16 09:00
can you share your recipe (or snippet) so I can see how you're using `docker_service` ?

**Comment by frezbo** [comment] 2017-02-16 11:59
@someara I have found the issue, I had a recipe that installs the latest kernel, so if I run the docker recipe after that it fails, so I changed the order and it seems to be working fine. I will close this once I have thoroughly tested it.

**Comment by someara** [comment] 2017-03-03 04:06
Closing this for now.

**Closed by someara** 2017-03-03 04:06 UTC
