### ISSUE TITLE
Undefined method `start' for nil:NilClass and container without name

### ISSUE THREAD

**Issue by manuelmazzuola** [chef-cookbooks/docker#540] opened 2015-11-03 15:36 UTC
This issue occures only if storage_driver is set to _overlay_
Works fine with _aufs_

cookbook version 2.2.2

```
NoMethodError
           -------------
           undefined method `start' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:244:in `block (3 levels) in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `call'
           /tmp/kitchen/cookbooks/docker/libraries/helpers_base.rb:67:in `with_retries'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:238:in `block (2 levels) in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:237:in `block in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:159:in `call_action'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:273:in `block in <class:DockerContainer>'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:159:in `call_action'
           /tmp/kitchen/cookbooks/docker/libraries/docker_container.rb:309:in `block in <class:DockerContainer>'

docker_container("sample-app") do
             action [:run]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :docker_container
             cookbook_name :"cd-docker"
             recipe_name "default"
             repo "busybox"
             detach true
             network_mode "host"
             tag "latest"
             log_driver "json-file"
             restart_policy "no"
             security_opts [""]
             signal "SIGKILL"
           end

```

It has created a container without the name
```
ubuntu@test-cd-docker:~$ sudo docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
ec0ef3235def        busybox:latest      "sh"                9 minutes ago       Created                                 

```

Docker info
```
ubuntu@test-cd-docker:~$ sudo docker info
Containers: 1
Images: 2
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 3.614 GiB
WARNING: No swap limit support
```

```
ubuntu@test-cd-docker:~$ uname -r
3.19.0-31-generic
```

**Comment by someara** [comment] 2015-11-09 19:53
Does the equivalent Docker CLI command behave the same way?

**Comment by chasebolt** [comment] 2015-12-10 00:26
@manuelmazzuola is this still an issue in v2.3.5?

**Comment by gionn** [comment] 2016-02-09 21:11
This should have been fixed somewhere recently, never see happening again, using overlay for over a month.

**Comment by someara** [comment] 2016-02-11 10:07
Can't reproduce this... Closing due to age.
Please re-open if this persists

**Closed by someara** 2016-02-11 10:07 UTC
Labels: question
