### ISSUE TITLE
volume in docker_container

### ISSUE THREAD

**Issue by onknows** [chef-cookbooks/docker#745] opened 2016-09-02 08:37 UTC
### Cookbook version

2.9.6
### Chef-client version

12.5
### Platform Details

Linux Ubuntu, VirtualBox Vagrant
### Scenario:

Volume creation using docker_container is not working I think
### Steps to Reproduce:

Use docker_container with volumes and container path. Run recipe and inspect container. No volumes are present.

```ruby
docker_container 'test-mail-server' do
  repo 'ok/test-mail-server' 
  port ["25:25",  "143:143"] 
  command 'supervisord -c /etc/supervisor.conf'
  # tty true # -t
  volumes '/var/lib/mysql'
end
```
### Expected Result:

I expect docker inspect to show this volume. When I run docker run manually with -v /var/lib/msql inspect does show
### Actual Result:

No volume in the contianer

**Comment by onknows** [comment] 2016-09-05 07:32
Documenten status

> volumes - An array of volume bindings for this container. Each volume binding is a string in one of these forms: container_path to create a new volume for the container. host_path:container_path to bind-mount a host path into the container. host_path:container_path:ro to make the bind-mount read-only inside the container.

I don't think this is true. This is not what happens. If I use {{volumes}} I never end up with a container with volumes. 

When I run a container manually using command line there is no problem.  I can setup the container the way I like to. 

This is a big problem because it is impossible to use volumes in any meaningful way.

**Comment by onknows** [comment] 2016-09-05 07:39
So it is not possible to run a container using `docker_container` with command line like below.

`sudo docker run --name test-mail-server-data -v /var/lib/msql -p 2203:22 -p 12323:12322 -p 9003:9001 -t -i ok/test-mail-server:latest supervisord -c /etc/supervisor-data.conf`

which would give me HostConfig similar to

```
        "HostConfig": {
        ....
            "Volumes": {
                "/var/lib/msql": {}
            },
```

When using `volumes` in `docker_container` not `Volumes` will be created

**Comment by someara** [comment] 2016-11-25 19:49
Hi.

I'm having trouble figuring this one out.... I believe it's somehow broken for you.... I'm just having trouble figuring out how.

The volumes property is exercised various times in the test cookbook....

For example... 

https://github.com/chef-cookbooks/docker/blob/9e073f3795587c48053869f83148399878bd680f/test/cookbooks/docker_test/recipes/container.rb#L324-L328

And the corresponding inspec here:

https://github.com/chef-cookbooks/docker/blob/9e073f3795587c48053869f83148399878bd680f/test/integration/resources-1123/inspec/assert_functioning_spec.rb#L364-L367

Everything seems to be in order...

I tried creating a container with volumes from the command line to compare the resulting JSON documents....

```
docker run \
  --name mysql-test \
  -e MYSQL_ROOT_PASSWORD=ilikerandompasswords \
  -d mysql/mysql-server:latest \
  -v /var/lib/mysql
```

This yielded 

```
# docker inspect -f '{{ .Config.Volumes }}' mysql-test
map[/var/lib/mysql:{}]
```

.... which looks the same as what the Chef recipe turns up.

```
docker inspect -f '{{ .HostConfig }}' mysql-test
{[]  {json-file map[]} default map[] {no 0} false  [] [] [] [] [] [] [] []   [] 0  false false false [] map[] map[]   67108864 map[] runc [0 0]  {0 0  0 [] [] [] [] [] 0 0   [] 0 0 0 0 0xc82033ba18 0xc82033ba22 0 [] 0 0 0 0}}
```

-s

**Comment by someara** [comment] 2016-11-25 19:49
What version of Docker are you using?

**Comment by someara** [comment] 2016-12-19 10:09
Cannot reproduce. 
Closing here for now... chime in and I'll re-open.

**Closed by someara** 2016-12-19 10:09 UTC
Labels: Type: Question
